spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb:http://CUSTOMER
          predicates:
            - Path=/api/v1/customer/**
        - id: order-service
          uri: lb:http://ORDER
          predicates:
            - Path=/api/v1/orders/**
        - id: order-line
          uri: lb:http://ORDER
          predicates:
            - Path=/api/v1/order-line/**
        - id: product-service
          uri: lb:http://PRODUCT
          predicates:
            - Path=/api/v1/product/**
        - id: payment-service
          uri: lb:http://PAYMENT
          predicates:
            - Path=/api/v1/payments/**
server:
  port: 1221