spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/MyEcom
  kafka:
    consumer:
      group-id: cartGroup
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5690/cart
    username: postgres
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
server:
  port: 2345
application:
  config:
    product-url: http://localhost:9999/api/v1/product
    order-url: http://localhost:9090/api/v1/orders
    customer-url: http://localhost:8090/api/v1/customer
keycloak:
  realm: MyEcom
  admin-client-id: service_cart
  admin-client-secret: i1mHGlWBokHwMnX9eSdHaxTQtyBibHNf
jwt:
  auth:
    convertor:
      resource-id: service_customer
      principle-attribute: preferred_username



