spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: '*'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/MyEcom
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/customer
    username: postgres
    password: pass
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
server:
  port: 8090

keycloak:
  auth-server-url: http://localhost:8080
  realm: MyEcom
  admin-client-id: service_customer
  admin-client-secret: bwpnYX1UjUOJLM3xC0as9FUkPDjTu3tu
jwt:
  secret: ph7KbB+EfyNiP0ttgxAWPSow6bn4d31/o2XrQDOwKno=
  auth:
    convertor:
      resource-id: service_customer
      principle-attribute: preferred_username

encryption:
  secret: 6pdryd1iUk4mX8msGhMnqomdunBheOzFF4zA44a7cMw=