spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/MyEcom
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:1234/product
    username: postgres
    password: pass
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  flyway:
    baseline-on-migrate: true
    baseline-description: "init"
    baseline-version: 0
    enabled: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations: classpath:db/migration,filesystem:./sql/migrations
    validate-on-migrate: true
    out-of-order: false
    clean-on-validation-error: false
jwt:
  auth:
    convertor:
      resource-id: service_product
      principle-attribute: preferred_username

server:
  port: 9999