-- Insert categories
INSERT INTO category (id, description) VALUES
                                           (1, 'Electronics'),
                                           (2, 'Clothing'),
                                           (3, 'Groceries'),
                                           (4, 'Books'),
                                           (5, 'Furniture'),
                                           (6, 'Sports Equipment'),
                                           (7, 'Toys'),
                                           (8, 'Beauty Products'),
                                           (9, 'Automotive'),
                                           (10, 'Jewelry');

-- Insert products
INSERT INTO product (id, name, available_quantity, price, category_id) VALUES
                                                                           (1, 'Smartphone', 100, 699.99, 1),
                                                                           (2, 'Laptop', 50, 999.99, 1),
                                                                           (3, 'LED TV', 30, 399.99, 1),
                                                                           (4, 'Headphones', 200, 49.99, 1),
                                                                           (5, 'Smartwatch', 150, 199.99, 1),
                                                                           (6, 'Jeans', 300, 29.99, 2),
                                                                           (7, 'T-shirt', 500, 9.99, 2),
                                                                           (8, 'Jacket', 100, 59.99, 2),
                                                                           (9, 'Shoes', 250, 39.99, 2),
                                                                           (10, 'Sweater', 150, 24.99, 2),
                                                                           (11, 'Apple', 1000, 0.99, 3),
                                                                           (12, 'Banana', 800, 0.49, 3),
                                                                           (13, 'Rice', 500, 1.99, 3),
                                                                           (14, 'Milk', 200, 2.49, 3),
                                                                           (15, 'Bread', 300, 1.49, 3),
                                                                           (16, 'Fiction Book', 200, 14.99, 4),
                                                                           (17, 'Cookbook', 100, 19.99, 4),
                                                                           (18, 'Notebook', 500, 2.99, 4),
                                                                           (19, 'Desk', 50, 149.99, 5),
                                                                           (20, 'Chair', 100, 79.99, 5),
                                                                           (21, 'Sofa', 30, 499.99, 5),
                                                                           (22, 'Dumbbells', 100, 49.99, 6),
                                                                           (23, 'Yoga Mat', 200, 19.99, 6),
                                                                           (24, 'Basketball', 150, 29.99, 6),
                                                                           (25, 'Action Figure', 300, 14.99, 7),
                                                                           (26, 'Puzzle', 200, 9.99, 7),
                                                                           (27, 'Dollhouse', 50, 59.99, 7),
                                                                           (28, 'Lipstick', 300, 19.99, 8),
                                                                           (29, 'Perfume', 150, 39.99, 8),
                                                                           (30, 'Face Cream', 200, 24.99, 8),
                                                                           (31, 'Car Wax', 100, 9.99, 9),
                                                                           (32, 'Tire Cleaner', 80, 14.99, 9),
                                                                           (33, 'Engine Oil', 50, 29.99, 9),
                                                                           (34, 'Necklace', 50, 99.99, 10),
                                                                           (35, 'Bracelet', 100, 49.99, 10),
                                                                           (36, 'Earrings', 200, 29.99, 10),
                                                                           (37, 'Tablet', 75, 399.99, 1),
                                                                           (38, 'Dress', 200, 59.99, 2),
                                                                           (39, 'Chicken', 300, 4.99, 3),
                                                                           (40, 'Mystery Novel', 150, 12.99, 4),
                                                                           (41, 'Bookshelf', 40, 199.99, 5),
                                                                           (42, 'Treadmill', 20, 799.99, 6),
                                                                           (43, 'Board Game', 100, 34.99, 7),
                                                                           (44, 'Shampoo', 200, 9.99, 8),
                                                                           (45, 'Car Seat Cover', 60, 49.99, 9),
                                                                           (46, 'Watch', 50, 199.99, 10),
                                                                           (47, 'Gaming Console', 30, 499.99, 1),
                                                                           (48, 'Winter Coat', 100, 89.99, 2),
                                                                           (49, 'Eggs', 500, 2.49, 3),
                                                                           (50, 'Self-Help Book', 120, 19.99, 4);
